version: "3.5"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db

  server:
    build:
      context: ./server
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/app
    command: "npx nodemon -L"

  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  ? db-data
